In [2]:
import numpy as np
import pandas as pd

# Data Frames
## Creating a DataFrames

In [3]:
data = {
    'Name' : ['Jhon', 'Peter', 'Linda', 'Anna'],
    'Age' : [28, 37, 49, 42],
    'City' : ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

In [4]:
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   Jhon   28  New York   65000
1  Peter   37     Paris   70000
2  Linda   49    Berlin   62000
3   Anna   42    London   85000

In [5]:
data_list = [
    ['Jhon', 28, 'New York', 65000],
    ['Anna', 37, 'Paris', 70000],
    ['Peter', 49, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

In [6]:
df2 = pd.DataFrame(data_list)
df2

       0   1         2      3
0   Jhon  28  New York  65000
1   Anna  37     Paris  70000
2  Peter  49    Berlin  62000
3  Linda  42    London  85000

In [7]:
columns = ['Name', 'Age', 'City', 'Salary']
df2 = pd.DataFrame(data_list, columns=columns)
df2

    Name  Age      City  Salary
0   Jhon   28  New York   65000
1   Anna   37     Paris   70000
2  Peter   49    Berlin   62000
3  Linda   42    London   85000

## Selection and Indexing of Columns

In [8]:
df2

    Name  Age      City  Salary
0   Jhon   28  New York   65000
1   Anna   37     Paris   70000
2  Peter   49    Berlin   62000
3  Linda   42    London   85000

In [9]:
df2[['Name', 'City']]

    Name      City
0   Jhon  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

## Creating a new Column

In [10]:
df2['Designation'] = ['Doctor', 'Teacher', 'Eng', 'Doctor']

In [11]:
df2

    Name  Age      City  Salary Designation
0   Jhon   28  New York   65000      Doctor
1   Anna   37     Paris   70000     Teacher
2  Peter   49    Berlin   62000         Eng
3  Linda   42    London   85000      Doctor

## Remove a Coloum

In [12]:
df2.drop('Designation', axis=1)

    Name  Age      City  Salary
0   Jhon   28  New York   65000
1   Anna   37     Paris   70000
2  Peter   49    Berlin   62000
3  Linda   42    London   85000

In [13]:
df2

    Name  Age      City  Salary Designation
0   Jhon   28  New York   65000      Doctor
1   Anna   37     Paris   70000     Teacher
2  Peter   49    Berlin   62000         Eng
3  Linda   42    London   85000      Doctor

## Selecting Rows

In [19]:
df2.loc[[0,1]]

   Name  Age      City  Salary Designation
0  Jhon   28  New York   65000      Doctor
1  Anna   37     Paris   70000     Teacher

In [20]:
df2.iloc[3]

Name            Linda
Age                42
City           London
Salary          85000
Designation    Doctor
Name: 3, dtype: object

In [22]:
df.loc[[0, 1]][['City', 'Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [24]:
df2.loc[[2, 3]][['Name', 'Age']]

    Name  Age
2  Peter   49
3  Linda   42

## Conditional Selection

In [26]:
df2[df2['Age'] > 30]

    Name  Age    City  Salary Designation
1   Anna   37   Paris   70000     Teacher
2  Peter   49  Berlin   62000         Eng
3  Linda   42  London   85000      Doctor

In [28]:
df2[(df2['Age'] > 30) & (df2['City'] == 'Paris')]

   Name  Age   City  Salary Designation
1  Anna   37  Paris   70000     Teacher